name: ghpage

on:
  push:
    branches: [ preparing-vercel ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        
    steps:
    - uses: actions/checkout@v3
    - run: |
          npm install --global vercel
          vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOEKN }}
          vercel deploy --token=${{ secrets.VERCEL_TOEKN }}